### ISSUE TITLE
URL broken (new link available)

### ISSUE THREAD

**Issue by SeanMcP** [mobilewood/Future-Friendly#5]
I can see this project is long dormant, but the URL [futurefriendlyweb.com](http://futurefriendlyweb.com/) no longer works: `ERR_NAME_NOT_RESOLVED`. 

For antiquity, I have forked and hosted this project on GitHub Pages here: https://seanmcp.github.io/Future-Friendly/

**Comment by binyamin** [comment]
@SeanMcP It's working for me now. Do you still have a problem?

**Comment by SeanMcP** [comment]
Looks like it is back! Thanks for checking @binyamin 🎉
